version: "3.7"

services:
  nodejs:
    build:
      context: .
      target: prod
    image: sanctuary-api
    container_name: sanctuary-api
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_HOSTNAME=db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:5.6.44
    container_name: sanctuary-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: .env
    expose:
      - "3306"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=sanctuary_dev

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
