version: "3.7"

services:
  nodejs:
    build:
      context: .
      target: prod
    image: sanctuary-api
    container_name: sanctuary-api
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=3306
      - MYSQL_DB=sanctuary_dev
    ports:
      - "80:8080"
    # volumes:
    #   - .:/home/node/app
    #   - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:3306 -- npm run start:prod
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sanctuary_dev
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
